name: My Cron

on:
  schedule:
    - cron: '10 * * * *'
      timezone: 'Asia/Seoul'

jobs:
  call-url:
    runs-on: ubuntu-latest

    steps:
      - name: Call URL
        run: curl -i "https://togijangi.jpg1.kr/claude_planner/public/noti.php"
