name: URL 실행

on:
  workflow_dispatch:

  schedule:
    - cron: '10 * * * *'
      timezone: 'Asia/Seoul'

jobs:
  call-url:
    runs-on: ubuntu-latest

    steps:
      - name: URL 호출
        run: curl -s -o /dev/null -w "%{http_code}" https://togijangi.jpg1.kr/claude_planner/public/noti.php"
